/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./RoleOption.module.css";

interface RoleOptionProps {
  title: string;
  isActive?: boolean;
}

export const RoleOption: React.FC<RoleOptionProps> = ({
  title,
  isActive = false,
}) => (
  <div className={`${styles.roleOption} ${isActive ? styles.active : ""}`}>
    <div className={styles.roleTitle}>{title}</div>
  </div>
);
