/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./SoraChainDashboard.module.css";
import { NavLink } from "./NavLink";
import { RoleOption } from "./RoleOption";

const navItems = [
  { text: "Home", width: "38px" },
  { text: "Create", width: "45px" },
  { text: "Tasks", width: "38px" },
  { text: "Leaderboard", width: "87px" },
];

const roleOptions = [
  { title: "Task Creator", width: "85px" },
  { title: "Aggregator/Validator", width: "143px" },
  { title: "Trainer", width: "47px" },
];

export const SoraChainDashboard: React.FC = () => {
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <div className={styles.logoSection}>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/ae1a574c40cc467faaa61354a5b36b7e/d1b3f2a77b4234f1d411faf80f19c7b260f1de2798b2578a476dffad6dfba351?apiKey=ae1a574c40cc467faaa61354a5b36b7e&"
            className={styles.logo}
            alt="SoraChain AI Logo"
          />
          <h1 className={styles.brandName}>SoraChain AI</h1>
        </div>

        <nav className={styles.navigation}>
          <div className={styles.navLinks}>
            {navItems.map((item) => (
              <NavLink key={item.text} text={item.text} />
            ))}
          </div>
          <button className={styles.connectWallet}>Connect wallet</button>
        </nav>
      </header>

      <main className={styles.mainContent}>
        <section className={styles.welcomeSection}>
          <h2 className={styles.welcomeTitle}>Welcome to SoraChain AI</h2>

          <nav className={styles.roleNavigation}>
            {roleOptions.map((role) => (
              <RoleOption key={role.title} title={role.title} />
            ))}
          </nav>

          <p className={styles.instructions}>
            Choose your role, connect your wallet and get started.
          </p>

          <button className={styles.continueButton}>
            Continue as Task Creator
          </button>
        </section>
      </main>
    </div>
  );
};
